QUERY_CREATE_TABLE_USERS = "CREATE TABLE IF NOT EXISTS USERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, ISADMIN INTEGER NOT NULL, USERNAME NVARCHAR(255) NOT NULL UNIQUE, PASSWORD VARBINARY(255) NOT NULL, SALT NVARCHAR(255) NOT NULL);"

QUERY_USERS_GET_SALT = '''SELECT SALT FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_GET_PASSWORD = '''SELECT PASSWORD FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_INSERT = '''INSERT INTO USERS (ISADMIN, USERNAME, PASSWORD, SALT) VALUES (?, ?, ?, ?)'''

QUERY_USERS_DELETE = '''DELETE FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_GET_ISADMIN = '''SELECT ISADMIN FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_UPDATE_PASSWORD = '''UPDATE USERS SET PASSWORD = ? WHERE USERNAME = ?'''

QUERY_USERS_UPDATE_USERNAME = '''UPDATE USERS SET USERNAME = ? WHERE USERNAME = ?'''
