QUERY_CREATE_TABLE_USERS = "CREATE TABLE IF NOT EXISTS USERS (USERNAME NVARCHAR(255) PRIMARY KEY, ISADMIN INTEGER NOT NULL, PASSWORD VARBINARY(255) NOT NULL, SALT NVARCHAR(255) NOT NULL, PICTURE NVARCHAR(1024) DEFAULT 'default.png', AUTHORIZED INTEGER NOT NULL);"

QUERY_CREATE_TABLE_SETTINGS = '''CREATE TABLE IF NOT EXISTS SETTINGS (RECORDLAUNCH INTEGER DEFAULT 0, RECORDINGDURATION FLOAT DEFAULT 5);'''

QUERY_CREATE_TABLE_AUTHORIZEDUSERS = '''CREATE TABLE IF NOT EXISTS AUTHORIZEDUSERS (USERNAME NVARCHAR(255) PRIMARY KEY);'''

QUERY_USERS_GET_SALT = '''SELECT SALT FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_GET_PASSWORD = '''SELECT PASSWORD FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_INSERT = '''INSERT INTO USERS (USERNAME, ISADMIN, PASSWORD, SALT, AUTHORIZED) VALUES (?, ?, ?, ?, ?);'''

QUERY_USERS_DELETE = '''DELETE FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_GET_ISADMIN = '''SELECT ISADMIN FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_UPDATE_PASSWORD = '''UPDATE USERS SET PASSWORD = ? WHERE USERNAME == ?;'''

QUERY_USERS_UPDATE_USERNAME = '''UPDATE USERS SET USERNAME = ? WHERE USERNAME == ?;'''

QUERY_USERS_UPDATE_PICTURE = '''UPDATE USERS SET PICTURE = ? WHERE USERNAME == ?;'''

QUERY_USERS_GET_PICTURE = '''SELECT PICTURE FROM USERS WHERE USERNAME == ?;'''

QUERY_USERS_UPDATE_AUTHORIZED = '''UPDATE USERS SET AUTHORIZED = ? WHERE USERNAME == ?;'''

QUERY_USERS_GET_AUTHORIZED = '''SELECT AUTHORIZED FROM USERS WHERE USERNAME == ?;'''

QUERY_SETTINGS_GET = '''SELECT ? FROM SETTINGS WHERE 1==1;'''

QUERY_SETTINGS_UPDATE = '''UPDATE SETTINGS SET ? = ? WHERE 1==1;'''
